### ISSUE TITLE
Change disclaimer page when user first opens wallet

### ISSUE THREAD

**Issue by Mawadda-Poly** [PolymathNetwork/extension#4]
Change copy to the following:

A couple of things to note before we begin:
- We do not collect keys and passwords in our servers
- This wallet does not use any trackers or analytics; however, some applications you connect the wallet to may use trackers or analytics. 
- Please read our Privacy Policy<https://polymath.network/polymesh-aldebaran-testnet/privacy-policy> to see what information we do collect and how it is processed.

Remove:
... we are not in the business . . .

If possible, can we add two checkboxes that must be checked before user continues:
1) I have read and accept the Polymath Privacy Policy <https://polymath.network/polymesh-aldebaran-testnet/privacy-policy>
2) I have read and accept the Polymath Terms of Service<https://polymath.network/polymesh-aldebaran-testnet/wallet-terms>

Change button copy to: Continue

**Comment by remon-nashid** [comment]
Also, change extension title that appears in browser extension page, from "Polymesh extension" to "Polymesh Simple Wallet"

**Comment by remon-nashid** [comment]
@Mawadda-Poly I'll try to add checkboxes to the disclaimer page, but if it ended up being complicated, can we just add another copy such as: "By using this extension, you agree to the following privacy policy and... "?

**Comment by Mawadda-Poly** [comment]
checking with Mohammed to see if this workaround is OK. he usually prefers checkboxes because it's more compliant but I'll keep you updated on his response

**Comment by remon-nashid** [comment]
@Mawadda-Poly I managed to add the checkboxes, but heads up that TOS link returns 404 https://polymath.network/polymesh-aldebaran-testnet/wallet-terms

**Comment by Mawadda-Poly** [comment]
Thanks, Remon. Yup, the ToS page hasn't been published yet but Brian is holding that URL for it.

For extension title, Brian has actually requested we change it to Aldebaran Testing Wallet

**Comment by remon-nashid** [comment]
Fixed via #5
